# Copyright (c) 2021, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set py_version=environ.get('CONDA_PY', 35) %}
{% set cuda_version='.'.join(environ.get('CUDA', '11.5').split('.')[:2]) %}

package:
  name: ptxcompiler
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda_{{ cuda_version }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numba >=0.54

test:
  requires:
    - pip
    - pytest

  commands:
    - pip check
    - python -c "from ptxcompiler import patch; patch.patch_numba_codegen_if_needed()"
    - pytest -v --pyargs ptxcompiler

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PTX Static compiler and Numba patch


