name: ptxcompiler wheels

on:
  push:
    branches:
      - 'pull-request/[0-9]+'
  workflow_call:
    inputs:
      versioneer-override:
        type: string
        default: ''
      build-tag:
        type: string
        default: ''
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string
      build-type:
        type: string
        default: nightly

concurrency:
  group: "ptxcompiler-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  ptxcompiler-wheels:
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux.yml@main
    with:
      repo: rapidsai/ptxcompiler

      build-type: ${{ inputs.build-type || 'pull-request' }}
      branch: ${{ inputs.branch }}
      sha: ${{ inputs.sha }}
      date: ${{ inputs.date }}

      package-name: ptxcompiler
      package-dir: .

      python-package-versioneer-override: ${{ inputs.versioneer-override }}
      python-package-build-tag: ${{ inputs.build-tag }}

      manylinux-container-amd64: "rapidsai/manylinux2014_118_x86_64"
      manylinux-container-arm64: "rapidsai/manylinux_2_31_118_aarch64"

      test-checkout-src: "false"
      test-unittest: "python -m pytest -v --pyargs ptxcompiler"
      test-extras: test
    secrets: inherit
